In [3]:
from google.colab import drive
drive.mount('/content/drive')
%cd '/content/drive/MyDrive/2023-02/금융데이터분석/MID_TERM_#1'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/2023-02/금융데이터분석/MID_TERM_#1

In [4]:
import pandas as pd
import numpy as np

In [5]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.10/dist-packages (9.0.0)
Requirement already satisfied: numpy>=1.16.6 in /usr/local/lib/python3.10/dist-packages (from pyarrow) (1.23.5)

# Load Data

In [6]:
stock_df = pd.read_parquet("주식_전체_December_from2000_edit.parquet", engine='pyarrow')
full_stock_df = pd.read_parquet("주식_전체_from2000_edit.parquet", engine='pyarrow') #contains daily stock data to calculate 최근 3개월, 최근 6개월, 최근 12개월 기간 동안의 수익률
acc_df=pd.read_parquet("A000020.동화약품~A123690.한국화장품_전처리파일_주식_December_from2000.parquet", engine='pyarrow')

In [7]:
stock_df

,code,year,month,종가(원),수정주가(원),상장주식수(주),시가총액,시가총액(천원),시가총액(조원)
0,A000020,2000,12,7159.523810,1391.285714,5.423568e+06,3.883016e+10,3.883016e+07,0.038830
1,A000020,2001,12,9269.047619,1853.809524,5.586294e+06,5.177963e+10,5.177963e+07,0.051780
2,A000020,2002,12,6880.000000,1376.000000,5.586294e+06,3.843370e+10,3.843370e+07,0.038434
3,A000020,2003,12,6724.782609,1344.956522,5.586294e+06,3.756661e+10,3.756661e+07,0.037567
4,A000020,2004,12,8661.739130,1732.347826,5.586294e+06,4.838702e+10,4.838702e+07,0.048387
...,...,...,...,...,...,...,...,...,...
47955,A950220,2017,12,NaN,NaN,NaN,NaN,NaN,NaN
47956,A950220,2018,12,NaN,NaN,NaN,NaN,NaN,NaN
47957,A950220,2019,12,NaN,NaN,NaN,NaN,NaN,NaN
47958,A950220,2020,12,NaN,NaN,NaN,NaN,NaN,NaN
47959,A950220,2021,12,10358.260870,10358.260870,9.857114e+07,1.021030e+12,1.021030e+09,1.021030

In [8]:
full_stock_df

,date,code,종가(원),수익률(%),수정계수,수정주가(원),상장주식수(주),거래대금(원),외국인보유비중(티커)(%),시가총액,year,month,quarter
5219,2000-01-03,A005930,266000.0,1.92,1.0,5320.0,149838777.0,3.919334e+11,47.090100,3.985711e+13,2000,1,1
5220,2000-01-04,A005930,305500.0,14.85,1.0,6110.0,149838777.0,4.442332e+11,47.288445,4.577575e+13,2000,1,1
5221,2000-01-05,A005930,279000.0,-8.67,1.0,5580.0,149838777.0,4.337834e+11,47.323193,4.180502e+13,2000,1,1
5222,2000-01-06,A005930,281000.0,0.72,1.0,5620.0,149838777.0,3.080053e+11,47.679093,4.210470e+13,2000,1,1
5223,2000-01-07,A005930,277000.0,-1.42,1.0,5540.0,149838777.0,2.227178e+11,47.706727,4.150534e+13,2000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24313535,2022-09-23,A050540,822.0,0.00,1.0,822.0,5118559.0,0.000000e+00,0.100751,4.207455e+09,2022,9,3
24313536,2022-09-26,A050540,822.0,0.00,1.0,822.0,5118559.0,0.000000e+00,0.100751,4.207455e+09,2022,9,3
24313537,2022-09-27,A050540,822.0,0.00,1.0,822.0,5118559.0,0.000000e+00,0.100751,4.207455e+09,2022,9,3
24313538,2022-09-28,A050540,822.0,0.00,1.0,822.0,5118559.0,0.000000e+00,0.100751,4.207455e+09,2022,9,3
24313539,2022-09-29,A050540,822.0,0.00,1.0,822.0,5118559.0,0.000000e+00,0.100751,4.207455e+09,2022,9,3

In [9]:
acc_df

,Symbol,Symbol Name,Kind,Item,Frequency,date,총자산(천원),총자산(평균)(천원),유동자산(천원),당좌자산(천원),...,"현금흐름(보통,직전4분기)(천원)",year,code,month,종가(원),수정주가(원),상장주식수(주),시가총액,시가총액(천원),시가총액(조원)
0,A000020,동화약품,NFS-IFRS(C),6000901001,ANNUAL,2000-12-31,2.544888e+08,2.429335e+08,1.851506e+08,1.682281e+08,...,NaN,2000,A000020,12.0,7159.523810,1391.285714,5423568.0,3.883016e+10,3.883016e+07,0.038830
1,A000020,동화약품,NFS-IFRS(C),6000901001,ANNUAL,2001-12-31,2.157472e+08,2.351180e+08,1.520965e+08,1.360110e+08,...,NaN,2001,A000020,12.0,9269.047619,1853.809524,5586294.0,5.177963e+10,5.177963e+07,0.051780
2,A000020,동화약품,NFS-IFRS(C),6000901001,ANNUAL,2002-12-31,2.014685e+08,2.086079e+08,1.430194e+08,1.257541e+08,...,NaN,2002,A000020,12.0,6880.000000,1376.000000,5586294.0,3.843370e+10,3.843370e+07,0.038434
3,A000020,동화약품,NFS-IFRS(C),6000901001,ANNUAL,2003-12-31,1.942339e+08,1.978512e+08,1.352872e+08,1.179294e+08,...,NaN,2003,A000020,12.0,6724.782609,1344.956522,5586294.0,3.756661e+10,3.756661e+07,0.037567
4,A000020,동화약품,NFS-IFRS(C),6000901001,ANNUAL,2004-12-31,1.952935e+08,1.947637e+08,1.352002e+08,1.173254e+08,...,NaN,2004,A000020,12.0,8661.739130,1732.347826,5586294.0,4.838702e+10,4.838702e+07,0.048387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37507,A123690,한국화장품,NFS-IFRS(C),6000901001,ANNUAL,2019-12-31,8.130796e+07,8.816450e+07,4.759443e+07,3.368020e+07,...,NaN,2019,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37508,A123690,한국화장품,NFS-IFRS(C),6000901001,ANNUAL,2020-12-31,7.537806e+07,7.834301e+07,4.700486e+07,3.406086e+07,...,NaN,2020,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37509,A123690,한국화장품,NFS-IFRS(C),6000901001,ANNUAL,2021-12-31,4.850845e+07,6.194325e+07,2.998707e+07,1.876161e+07,...,NaN,2021,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37510,A123690,한국화장품,NFS-IFRS(C),6000901001,ANNUAL,2022-12-31,NaN,NaN,NaN,NaN,...,NaN,2022,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37511,A123690,한국화장품,NFS-IFRS(C),6000901001,ANNUAL,2023-02-08,NaN,NaN,NaN,NaN,...,NaN,2023,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Merge the dataframes based on 'code', 'year', and 'month'
merged_data = pd.merge(stock_df,acc_df, on=['code', 'year', 'month'], how='left')

# Remove duplicate columns
merged_data = merged_data.loc[:, ~merged_data.columns.duplicated()]

merged_data

,code,year,month,종가(원)_x,수정주가(원)_x,상장주식수(주)_x,시가총액_x,시가총액(천원)_x,시가총액(조원)_x,Symbol,...,현금흐름(직전4분기)(천원),현금흐름(보통)(천원),"현금흐름(보통,연율화)(천원)","현금흐름(보통,직전4분기)(천원)",종가(원)_y,수정주가(원)_y,상장주식수(주)_y,시가총액_y,시가총액(천원)_y,시가총액(조원)_y
0,A000020,2000,12,7159.523810,1391.285714,5.423568e+06,3.883016e+10,3.883016e+07,0.038830,A000020,...,NaN,7781416.0,7781416.0,NaN,7159.523810,1391.285714,5423568.0,3.883016e+10,3.883016e+07,0.038830
1,A000020,2001,12,9269.047619,1853.809524,5.586294e+06,5.177963e+10,5.177963e+07,0.051780,A000020,...,NaN,9471174.0,9471174.0,NaN,9269.047619,1853.809524,5586294.0,5.177963e+10,5.177963e+07,0.051780
2,A000020,2002,12,6880.000000,1376.000000,5.586294e+06,3.843370e+10,3.843370e+07,0.038434,A000020,...,NaN,10791135.0,10791135.0,NaN,6880.000000,1376.000000,5586294.0,3.843370e+10,3.843370e+07,0.038434
3,A000020,2003,12,6724.782609,1344.956522,5.586294e+06,3.756661e+10,3.756661e+07,0.037567,A000020,...,NaN,8378307.0,8378307.0,NaN,6724.782609,1344.956522,5586294.0,3.756661e+10,3.756661e+07,0.037567
4,A000020,2004,12,8661.739130,1732.347826,5.586294e+06,4.838702e+10,4.838702e+07,0.048387,A000020,...,NaN,9816105.0,9816105.0,NaN,8661.739130,1732.347826,5586294.0,4.838702e+10,4.838702e+07,0.048387
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47955,A950220,2017,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47956,A950220,2018,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47957,A950220,2019,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47958,A950220,2020,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47959,A950220,2021,12,10358.260870,10358.260870,9.857114e+07,1.021030e+12,1.021030e+09,1.021030,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
columns_to_remove_y = ['종가(원)_y', '수정주가(원)_y', '상장주식수(주)_y', '시가총액_y', '시가총액(천원)_y', '시가총액(조원)_y']
cleaned_data = merged_data.drop(columns=columns_to_remove_y)
# Rename columns to remove the '_x'
cleaned_data.rename(columns={
    '종가(원)_x': '종가(원)',
    '수정주가(원)_x': '수정주가(원)',
    '상장주식수(주)_x': '상장주식수(주)',
    '시가총액_x': '시가총액',
    '시가총액(천원)_x': '시가총액(천원)',
    '시가총액(조원)_x': '시가총액(조원)'
}, inplace=True)

# 1.1. 4 Factor 전략

#### 밸류팩터

먼저 밸류 지표에 해당하는 이익수익률을 계산해보겠습니다. 이익수익률은 이자 및 법인세 차감전이익(EBIT)을 기업가치(시가총액 + 순차입금)로 나눈 값입니다. 이를 분해하면 다음과 같습니다.

\begin{equation*}
\begin{split}
이익수익률 & = \frac{이자\,및\,법인세\,차감전이익}{기업\,가치} \\
& = \frac{이자\,및\,법인세\,차감전이익}{시가총액 + 순차입금} \\
& = \frac{당기순이익 + 법인세 + 이자비용}{시가총액 + 총부채 - 여유자금} \\
& = \frac{당기순이익 + 법인세 + 이자비용}{시가총액 + 총부채 - (현금 - max(0, 유동부채 - 유동자산 + 현금))}
\end{split}
\end{equation*}

**밸류 index**: PER, PBR, PSR, PCR

In [12]:
# EPS and BPS for PBR and PER
cleaned_data['EPS'] = cleaned_data['지배주주순이익(천원)'] / cleaned_data['상장주식수(주)'] * 1000  # multiply by 1000 to convert 천원 to 원
cleaned_data['BPS'] = cleaned_data['지배주주순자산(자사주차감전)(천원)'] / cleaned_data['상장주식수(주)'] * 1000  # multiply by 1000 to convert 천원 to 원

# Calculate PBR
cleaned_data['PBR'] = cleaned_data['종가(원)'] / cleaned_data['BPS']

# Calculate PER
cleaned_data['PER'] = cleaned_data['종가(원)'] / cleaned_data['EPS']

# Calculate PCR
cleaned_data['CFO'] = cleaned_data['영업활동으로인한현금흐름(천원)'] / cleaned_data['상장주식수(주)'] * 1000  # Cash flow per share
cleaned_data['PCR'] = cleaned_data['종가(원)'] / cleaned_data['CFO']

# Calculate PSR
cleaned_data['SPS'] = cleaned_data['매출액(천원)'] / cleaned_data['상장주식수(주)'] * 1000  # Sales per share
cleaned_data['PSR'] = cleaned_data['종가(원)'] / cleaned_data['SPS']


cleaned_data[['PBR', 'PER', 'PCR','PSR']].head()

        PBR       PER       PCR       PSR
0  0.298478  9.478970  3.693834  0.307144
1  0.384645  7.484989  1.691597  0.385992
2  0.268210  4.426157  1.887665  0.286002
3  0.256521  6.321048  1.968212  0.305389
4  0.320278  6.517467  2.056591  0.350728

In [13]:
#NA처리
columns_to_check = ['PER', 'PBR', 'PCR', 'PSR']

for column in columns_to_check:
    inf_rows_pos = cleaned_data[cleaned_data[column] == float('inf')]
    inf_rows_neg = cleaned_data[cleaned_data[column] == float('-inf')]

    if not inf_rows_pos.empty:
        print(f"Entries in {column} with 'inf':")
        print(inf_rows_pos[['year', 'Symbol', column]])

    if not inf_rows_neg.empty:
        print(f"Entries in {column} with '-inf':")
        print(inf_rows_neg[['year', 'Symbol', column]])

    # Replace infinities with NaN
    cleaned_data[column].replace([float('inf'), float('-inf')], np.nan, inplace=True)

Entries in PER with 'inf':
      year   Symbol  PER
4511  2001  A005110  inf
Entries in PCR with 'inf':
       year   Symbol  PCR
24     2002  A000040  inf
660    2000  A000700  inf
792    2000  A000890  inf
968    2000  A001060  inf
1122   2000  A001210  inf
...     ...      ...  ...
26186  2006  A086980  inf
26802  2006  A090350  inf
26890  2006  A090430  inf
27308  2006  A092230  inf
27572  2006  A093370  inf

[255 rows x 3 columns]
Entries in PSR with 'inf':
       year   Symbol  PSR
4511   2001  A005110  inf
6465   2019  A008060  inf
17368  2010  A043710  inf
22257  2015  A066430  inf

In [14]:
# Calculate the rank for each metric
cleaned_data['PBR_rank'] = cleaned_data.groupby('year')['PBR'].transform(lambda x: x.rank(ascending=True))
cleaned_data['PER_rank'] = cleaned_data.groupby('year')['PER'].transform(lambda x: x.rank(ascending=True))
cleaned_data['PCR_rank'] = cleaned_data.groupby('year')['PCR'].transform(lambda x: x.rank(ascending=True))
cleaned_data['PSR_rank'] = cleaned_data.groupby('year')['PSR'].transform(lambda x: x.rank(ascending=True))

# Calculate the factor_value
columns_for_factor_value = ['PBR_rank', 'PCR_rank', 'PER_rank', 'PSR_rank']
cleaned_data['factor_value'] = cleaned_data.groupby('year')[columns_for_factor_value].transform(lambda x: (x - np.nanmean(x)) / np.nanstd(x)).sum(axis=1)

# Display the result
cleaned_data[['year', 'PBR_rank', 'PCR_rank', 'PER_rank', 'PSR_rank', 'factor_value']].head()
cleaned_data

,code,year,month,종가(원),수정주가(원),상장주식수(주),시가총액,시가총액(천원),시가총액(조원),Symbol,...,PER,CFO,PCR,SPS,PSR,PBR_rank,PER_rank,PCR_rank,PSR_rank,factor_value
0,A000020,2000,12,7159.523810,1391.285714,5.423568e+06,3.883016e+10,3.883016e+07,0.038830,A000020,...,9.478970,1938.236416,3.693834,23310.025983,0.307144,188.0,439.0,421.0,341.0,0.255252
1,A000020,2001,12,9269.047619,1853.809524,5.586294e+06,5.177963e+10,5.177963e+07,0.051780,A000020,...,7.484989,5479.464203,1.691597,24013.598103,0.385992,189.0,423.0,298.0,374.0,-1.068092
2,A000020,2002,12,6880.000000,1376.000000,5.586294e+06,3.843370e+10,3.843370e+07,0.038434,A000020,...,4.426157,3644.715262,1.887665,24055.755032,0.286002,111.0,379.0,347.0,366.0,-1.947432
3,A000020,2003,12,6724.782609,1344.956522,5.586294e+06,3.756661e+10,3.756661e+07,0.037567,A000020,...,6.321048,3416.696830,1.968212,22020.382386,0.305389,117.0,465.0,341.0,418.0,-1.672556
4,A000020,2004,12,8661.739130,1732.347826,5.586294e+06,4.838702e+10,4.838702e+07,0.048387,A000020,...,6.517467,4211.698131,2.056591,24696.490553,0.350728,176.0,557.0,372.0,515.0,-0.889972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47955,A950220,2017,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
47956,A950220,2018,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
47957,A950220,2019,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
47958,A950220,2020,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
47959,A950220,2021,12,10358.260870,10358.260870,9.857114e+07,1.021030e+12,1.021030e+09,1.021030,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000

In [15]:
#Value factor  with eq

# Compute the components of the formula using the acc_df
acc_df['여유자금'] = acc_df['유동부채(천원)'] - acc_df['유동자산(천원)'] + acc_df['현금및현금성자산(천원)']

# Compute the Value factor (Earnings Yield)
acc_df['Value_factor'] = (acc_df['지배주주순이익(천원)'] + acc_df['법인세비용(천원)'] + acc_df['이자비용(비영업)(천원)']) / (acc_df['시가총액(천원)'] + acc_df['총부채(천원)'] - acc_df['여유자금'])

### Rank the Value factor for each year #높을수록 value 지표 높다=좋다
#acc_df['Value_rank'] = acc_df.groupby('year')['Value_factor'].rank(method='min', ascending=False)

acc_df['Value_factor'].head()

0    0.055764
1    0.069900
2    0.074013
3    0.049720
4    0.050111
Name: Value_factor, dtype: float64

#### 퀄리티팩터


다음으로 퀄리티 지표에 해당하는 투하자본 수익률을 계산하겠습니다. 해당 값은 이자 및 법인세 차감전이익(EBIT)를 투하자본(IC)으로 나누어 계산되며, 이를 분해하면 다음과 같습니다.

\begin{equation*}
\begin{split}
투하자본\,수익률 & = \frac{이자\,및\,법인세\,차감전이익}{투하자본} \\
& = \frac{당기순이익 + 법인세 + 이자비용}{(유동자산 - 유동부채) + (비유동자산 - 감가상각비)}
\end{split}
\end{equation*}

**Quality index**: 자기자본이익률 roe, 매출총이익 gpa, 영업활동현금흐름 cfo

In [16]:
# Calculate the metrics
cleaned_data['ROE'] = cleaned_data['지배주주순이익(천원)'] / cleaned_data['총자본(천원)']
cleaned_data['GPA'] = cleaned_data['매출총이익(천원)'] / cleaned_data['총자산(천원)']
cleaned_data['CFO'] = cleaned_data['영업활동으로인한현금흐름(천원)'] / cleaned_data['총자산(천원)']

# Calculate the rank for each metric
cleaned_data['ROE_rank'] = cleaned_data.groupby('year')['ROE'].transform(lambda x: x.rank(ascending=True))
cleaned_data['GPA_rank'] = cleaned_data.groupby('year')['GPA'].transform(lambda x: x.rank(ascending=True))
cleaned_data['CFO_rank'] = cleaned_data.groupby('year')['CFO'].transform(lambda x: x.rank(ascending=True))

# Calculate the factor_quality
columns_for_factor_quality = ['ROE_rank', 'GPA_rank', 'CFO_rank']
cleaned_data['factor_quality'] = cleaned_data.groupby('year')[columns_for_factor_quality].transform(lambda x: (x - np.nanmean(x)) / np.nanstd(x)).sum(axis=1)

# Display the result
cleaned_data[['year', 'ROE_rank', 'GPA_rank', 'CFO_rank', 'factor_quality']].head()

   year  ROE_rank  GPA_rank  CFO_rank  factor_quality
0  2000     290.0     564.0     491.0       -0.725433
1  2001     428.0     855.0     897.0        1.553908
2  2002     473.0     950.0     742.0        1.139090
3  2003     411.0     930.0     833.0        1.024468
4  2004     425.0     992.0     945.0        1.217203

In [17]:
#Quality factor with eq
acc_df['Quality_factor'] = (acc_df['지배주주순이익(천원)'] + acc_df['법인세비용(천원)'] + acc_df['이자비용(천원)']) / (acc_df['유동자산(천원)'] + acc_df['유동부채(천원)'] + acc_df['비유동자산(천원)'] - acc_df['유형자산감가상각비(천원)'])
acc_df['Quality_factor'].head()

0    0.018209
1    0.032513
2    0.035311
3    0.025823
4    0.032679
Name: Quality_factor, dtype: float64

##모멘텀팩터

In [18]:
#Momentum factor_근 3개월, 최근 6개월, 최근 12개월 기간 동안의 수익률, 단, 최근 1개월은 수익률 계산하는 샘플 기간에서 뺌

# Group by Symbol and year, then apply the momentum calculations
def compute_momentum_factors(group):
    # Calculate the logarithmic returns
    ret = np.log(group['종가(원)']) - np.log(group['종가(원)']).shift(1)

    # Compute the momentum factors
    mom_3m = (1 + ret).iloc[-60:].prod() - 1
    mom_6m = (1 + ret).iloc[-120:].prod() - 1
    mom_12m = (1 + ret).iloc[-252:].prod() - 1

    return pd.Series({'mom_3m': mom_3m, 'mom_6m': mom_6m, 'mom_12m': mom_12m})

# Grouping by stock Symbol and year, and applying the function
momentum_data = full_stock_df.groupby(['code', 'year']).apply(compute_momentum_factors).reset_index()

# Ranking the momentum factors in descending order for each year
momentum_data[['mom_3m_rank', 'mom_6m_rank', 'mom_12m_rank']] = momentum_data[['year', 'mom_3m', 'mom_6m', 'mom_12m']].groupby('year').rank(ascending=False, method='min')

# Calculating the scaled ranking for each momentum rank and summing across the three momentum factors
momentum_data['factor_mom'] = momentum_data[['year', 'mom_3m_rank', 'mom_6m_rank', 'mom_12m_rank']].groupby('year').transform(lambda x: (x - np.nanmean(x)) / np.nanstd(x)).sum(axis=1)


momentum_data.head()

,code,year,mom_3m,mom_6m,mom_12m,mom_3m_rank,mom_6m_rank,mom_12m_rank,factor_mom
0,A000020,2000,-0.286975,-0.408366,-0.761024,1823.0,1827.0,1981.0,4.742367
1,A000020,2001,0.265734,-0.054090,0.077586,239.0,1691.0,205.0,-0.060720
2,A000020,2002,-0.067533,-0.125231,-0.362730,1669.0,1496.0,1692.0,3.451243
3,A000020,2003,-0.130696,-0.096839,-0.039286,1995.0,1708.0,1615.0,4.511388
4,A000020,2004,0.168222,0.184107,0.170608,187.0,290.0,173.0,-2.391863

In [19]:
# Merging cleaned_data with the modified momentum_data_copy on 'code' and 'year'
merged_df_final = pd.merge(cleaned_data, momentum_data, on=['code', 'year'], how='left')

merged_df_final

,code,year,month,종가(원),수정주가(원),상장주식수(주),시가총액,시가총액(천원),시가총액(조원),Symbol,...,GPA_rank,CFO_rank,factor_quality,mom_3m,mom_6m,mom_12m,mom_3m_rank,mom_6m_rank,mom_12m_rank,factor_mom
0,A000020,2000,12,7159.523810,1391.285714,5.423568e+06,3.883016e+10,3.883016e+07,0.038830,A000020,...,564.0,491.0,-0.725433,-0.286975,-0.408366,-0.761024,1823.0,1827.0,1981.0,4.742367
1,A000020,2001,12,9269.047619,1853.809524,5.586294e+06,5.177963e+10,5.177963e+07,0.051780,A000020,...,855.0,897.0,1.553908,0.265734,-0.054090,0.077586,239.0,1691.0,205.0,-0.060720
2,A000020,2002,12,6880.000000,1376.000000,5.586294e+06,3.843370e+10,3.843370e+07,0.038434,A000020,...,950.0,742.0,1.139090,-0.067533,-0.125231,-0.362730,1669.0,1496.0,1692.0,3.451243
3,A000020,2003,12,6724.782609,1344.956522,5.586294e+06,3.756661e+10,3.756661e+07,0.037567,A000020,...,930.0,833.0,1.024468,-0.130696,-0.096839,-0.039286,1995.0,1708.0,1615.0,4.511388
4,A000020,2004,12,8661.739130,1732.347826,5.586294e+06,4.838702e+10,4.838702e+07,0.048387,A000020,...,992.0,945.0,1.217203,0.168222,0.184107,0.170608,187.0,290.0,173.0,-2.391863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47955,A950220,2017,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,864.0,532.0,581.0,-1.766642
47956,A950220,2018,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,234.0,246.0,280.0,-3.636982
47957,A950220,2019,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,935.0,524.0,607.0,-1.780344
47958,A950220,2020,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.000000,0.000000,0.000000,0.000000,1164.0,1275.0,822.0,0.058836
47959,A950220,2021,12,10358.260870,10358.260870,9.857114e+07,1.021030e+12,1.021030e+09,1.021030,NaN,...,NaN,NaN,0.000000,-0.010710,-0.078719,-0.364628,1049.0,746.0,1835.0,0.600379

##Growth factor

In [20]:
#Growth factor
# Calculating log growth rates for the specified indices
indices = ["매출액(천원)", "매출총이익(천원)", "영업이익(천원)", "지배주주순이익(천원)"]

for index in indices:
    growth_rate_col_name = f"{index}_growth_rate"
    merged_df_final[growth_rate_col_name] = merged_df_final.groupby('Symbol')[index].apply(lambda x: np.log(x / x.shift(1)))

growth_rate_cols = [f"{index}_growth_rate" for index in indices]
merged_df_final['GrowthFactor'] = merged_df_final[growth_rate_cols].mean(axis=1)
merged_df_final['GrowthFactor'].head()

/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-20-90f090d8dc2e>:7: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  merged_df_final[growth_rate_col_name] = merged_df_final.groupby('Symbol')[index].apply(lambda x: np.log(x / x.shift(1)))
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-20-90f090d8dc2e>:7: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  merged_df_final[growth_rate_col_name] = merged_df_final.groupby('Symbol')[index].apply(lambda x: np.log(x / x.shift(1)))
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-20-90f090d8dc2e>:7: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  merged_df_final[growth_rate_col_name] = merged_df_final.groupby('Symbol')[index].apply(lambda x: np.log(x / x.shift(1)))
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
<ipython-input-20-90f090d8dc2e>:7: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  merged_df_final[growth_rate_col_name] = merged_df_final.groupby('Symbol')[index].apply(lambda x: np.log(x / x.shift(1)))

0         NaN
1    0.225537
2    0.120360
3   -0.261243
4    0.184863
Name: GrowthFactor, dtype: float64

#4가지 factor 결합

In [22]:
def select_top_30_stocks_weighted(data, year, weights):
    """
    Select the top 30 stocks for the given year based on the weighted combined rank of value, quality, momentum, and growth factors.

    Parameters:
    - data: DataFrame containing the stock data
    - year: Target year for which top 30 stocks are to be selected
    - weights: A list or tuple containing weights for value, quality, momentum, and growth factors respectively

    Returns:
    - DataFrame containing the top 30 stocks and their ranks for the specified year
    """

    # Filtering the data for the target year
    year_data = data[data['year'] == year].copy()  # Using copy() to avoid SettingWithCopyWarning

    # Ranking for each factor
    year_data['Value_rank'] = year_data['factor_value'].rank(ascending=False)
    year_data['Quality_rank'] = year_data['factor_quality'].rank(ascending=False)
    year_data['Momentum_rank'] = year_data['factor_mom'].rank(ascending=False)
    year_data['Growth_rank'] = year_data['GrowthFactor'].rank(ascending=False)

    # Calculate the weighted score
    year_data['weighted_score'] = weights[0] * year_data['Value_rank'] + \
                                  weights[1] * year_data['Quality_rank'] + \
                                  weights[2] * year_data['Momentum_rank'] + \
                                  weights[3] * year_data['Growth_rank']

    # Selecting the top 30 stocks based on the weighted score
    top_30_stocks = year_data.nsmallest(30, 'weighted_score')

    return top_30_stocks[['Symbol', 'Symbol Name']]

equal_weights = (0.25, 0.25, 0.25, 0.25)
select_top_30_stocks_weighted(merged_df_final, 2021, equal_weights)

        Symbol Symbol Name
14761  A035720         카카오
19095  A051910        LG화학
26905  A090430      아모레퍼시픽
30645  A115610        이미지스
22945  A068760      셀트리온제약
10537  A018290      브이티지엠피
17687  A045340       토탈소프트
21053  A060250  NHN한국사이버결제
22901  A068330       일신바이오
19073  A051900      LG생활건강
22857  A068270        셀트리온
19469  A053030        바이넥스
19689  A053580         웹케시
23957  A074430      아미노로직스
5433   A006280         녹십자
2573   A002790        아모레G
30183  A111710        남화산업
19601  A053290        NE능률
13243  A031430    신세계인터내셔날
28577  A099390     브레인즈컴퍼니
6863   A008930      한미사이언스
12979  A030190    NICE평가정보
22725  A067730        로지시스
26157  A086900        메디톡스
22505  A067000        조이시티
6181   A007570        일양약품
13683  A032820        우리기술
18435  A049180        셀루메드
6577   A008350       남선알미늄
15729  A037950         엘컴텍

In [23]:
##포트폴리오_30 return 및 volatility 계산
def select_top_30_stocks_weighted(data, year, weights, full_stock_df):
    """
    Select the top 30 stocks for the given year based on the weighted combined rank of value, quality, momentum, and growth factors.
    Calculate the 수익률 and volatility for each of the top 30 stocks over the evaluation period.

    Parameters:
    - data: DataFrame containing the stock data
    - year: Target year for which top 30 stocks are to be selected
    - weights: A list or tuple containing weights for value, quality, momentum, and growth factors respectively
    - full_stock_df: DataFrame containing daily stock returns

    Returns:
    - DataFrame containing the top 30 stocks, their average daily return, and annualized volatility for the evaluation period
    """

    # Filtering the data for the target year
    year_data = data[data['year'] == year].copy()  # Using copy() to avoid SettingWithCopyWarning

    # Ranking for each factor
    year_data['Value_rank'] = year_data['factor_value'].rank(ascending=False)
    year_data['Quality_rank'] = year_data['factor_quality'].rank(ascending=False)
    year_data['Momentum_rank'] = year_data['factor_mom'].rank(ascending=False)
    year_data['Growth_rank'] = year_data['GrowthFactor'].rank(ascending=False)

    # Calculate the weighted score
    year_data['weighted_score'] = weights[0] * year_data['Value_rank'] + \
                                  weights[1] * year_data['Quality_rank'] + \
                                  weights[2] * year_data['Momentum_rank'] + \
                                  weights[3] * year_data['Growth_rank']

    # Selecting the top 30 stocks based on the weighted score
    top_30_stocks = year_data.nsmallest(30, 'weighted_score')
    top_30_symbols = top_30_stocks['Symbol'].tolist()

    # Define the evaluation period based on the given year
    start_date = f"{year + 1}-04-01"
    end_date = f"{year + 2}-03-31"

    # Filter the stock data for the evaluation period and the top 30 stocks
    eval_period_data = full_stock_df[(full_stock_df['date'] >= start_date) &
                                     (full_stock_df['date'] <= end_date) &
                                     (full_stock_df['code'].isin(top_30_symbols))]

    # Calculate the average daily return and the annualized volatility for each stock
    stock_summary = eval_period_data.groupby('code').agg(
        수익률=('수익률(%)', 'mean'),
        volatility=('수익률(%)', lambda x: x.std() * np.sqrt(252))  # 252 trading days in a year
    ).reset_index()

    # Merge the summary data with top 30 stocks
    result = pd.merge(top_30_stocks[['Symbol', 'Symbol Name']], stock_summary, left_on='Symbol', right_on='code', how='left')
    result = result[['Symbol', 'Symbol Name', '수익률', 'volatility']]

    return result

equal_weights = (0.00, 0.50, 0.50, 0.00)
select_top_30_stocks_weighted(merged_df_final, 2001, equal_weights, full_stock_df)

     Symbol  Symbol Name       수익률  volatility
0   A033920           무학  0.046858   79.701843
1   A035250         강원랜드 -0.243870   52.184575
2   A036530       SNT홀딩스 -0.369962   60.404863
3   A000400       롯데손해보험 -0.029770   50.894775
4   A052330           코텍 -0.400000   69.791437
5   A044960          이글벳 -0.147433   85.291987
6   A017370        우신시스템 -0.149502   81.750847
7   A045520      크린앤사이언스 -0.090460   55.949414
8   A036670          KCI -0.182605   64.240477
9   A058470         리노공업 -0.306897   65.022062
10  A003120         일성신약 -0.252682   42.983575
11  A003800        에이스침대 -0.098966   43.006365
12  A018680         서울제약 -0.175249   62.469577
13  A008700         아남전자 -0.510421   76.126938
14  A041830          인바디 -0.144253   45.916982
15  A054940        엑사이엔씨 -0.201916   74.640396
16  A014190         원익큐브 -0.071188   47.565038
17  A036640          HRS  0.183755   81.355790
18  A046070          코다코 -0.141992   58.389958
19  A018310        삼목에스폼 -0.117203   53.133560
20  A054620       APS홀딩스 -0.559387   78.275881
21  A041650       상신브레이크 -0.262261   61.901644
22  A056360          코위버 -0.441533   72.853873
23  A004960         한신공영 -0.415900  110.189038
24  A010820          퍼스텍 -0.183870   71.242436
25  A033270      유나이티드제약 -0.013563   48.361384
26  A053800           안랩 -0.427280   68.998794
27  A026040       제이에스티나 -0.220038   56.022658
28  A003060  에이프로젠바이오로직스 -0.220268   84.810519
29  A017650         대림제지 -0.330958   43.709389

In [24]:
# Strategy weight configurations
strategy_weights = {
    'equal_weight': [0.25, 0.25, 0.25, 0.25],
    'growth_quality_weight': [0.00, 0.50, 0.00, 0.50],
    'growth_quality_momentum_weight': [0.00, 0.333, 0.333, 0.333],
    'momentum_quality_weight': [0.00, 0.50, 0.50, 0.00],
    'value_quality_weight': [0.50, 0.50, 0.00, 0.00]
}

equal_weights = (0.00, 0.50, 0.50, 0.00)
growth_quality_weight= (0.00, 0.50, 0.00, 0.50)
growth_quality_momentum_weight= (0.00, 0.333, 0.333, 0.333)
momentum_quality_weight= (0.00, 0.50, 0.50, 0.00)
value_quality_weight= (0.50, 0.50, 0.00, 0.0)

In [25]:
def portfolio_stats(data, year, weights, full_stock_df):

    # Filtering the data for the target year
    year_data = data[data['year'] == year].copy()

    # Ranking for each factor
    year_data['Value_rank'] = year_data['factor_value'].rank(ascending=False)
    year_data['Quality_rank'] = year_data['factor_quality'].rank(ascending=False)
    year_data['Momentum_rank'] = year_data['factor_mom'].rank(ascending=False)
    year_data['Growth_rank'] = year_data['GrowthFactor'].rank(ascending=False)

    # Calculate the weighted score
    year_data['weighted_score'] = sum(w * year_data[factor + '_rank'] for w, factor in zip(weights, ['Value', 'Quality', 'Momentum', 'Growth']))

    # Selecting the top 30 stocks based on the weighted score
    top_30_stocks = year_data.nsmallest(30, 'weighted_score')
    top_30_symbols = top_30_stocks['Symbol'].tolist()

    # Define the evaluation period based on the given year
    start_date = f"{year + 1}-04-01"
    end_date = f"{year + 2}-03-31"

    # Filter the stock data for the evaluation period and the top 30 stocks
    eval_period_data = full_stock_df[(full_stock_df['date'] >= start_date) &
                                     (full_stock_df['date'] <= end_date) &
                                     (full_stock_df['code'].isin(top_30_symbols))]

    # Calculate the average daily return and the annualized volatility for each stock
    stock_summary = eval_period_data.groupby('code').agg(
        수익률=('수익률(%)', 'mean'),
        volatility=('수익률(%)', lambda x: x.std() * np.sqrt(252))  # 252 trading days in a year
    ).reset_index()

    # Calculate portfolio return and volatility
    portfolio_return = stock_summary['수익률'].mean()
    portfolio_volatility = np.sqrt((stock_summary['volatility']**2).mean())

    return portfolio_return, portfolio_volatility

In [26]:
# Create empty dataframes to store results
portfolio_returns_df = pd.DataFrame(index=range(2001, 2021), columns=strategy_weights.keys())
portfolio_volatility_df = pd.DataFrame(index=range(2001, 2021), columns=strategy_weights.keys())


# Loop through each year and each strategy weight
for year in range(2001, 2021):
    for strategy, weight in strategy_weights.items():
        try:
            # Get the top 30 stocks for the given year and weight
            top_30_stocks = select_top_30_stocks_weighted(merged_df_final, year, weight, stock_df)

            # Compute the portfolio return and volatility
            portfolio_return = top_30_stocks['수익률'].mean()
            portfolio_volatility = np.sqrt((top_30_stocks['volatility']**2).mean())

            # Store the results in respective dataframes
            portfolio_returns_df.at[year, strategy] = portfolio_return
            portfolio_volatility_df.at[year, strategy] = portfolio_volatility

        except Exception as e:
            print(f"Error for year {year} and strategy {strategy}: {e}")

portfolio_returns_df, portfolio_volatility_df

Error for year 2001 and strategy equal_weight: 'date'
Error for year 2001 and strategy growth_quality_weight: 'date'
Error for year 2001 and strategy growth_quality_momentum_weight: 'date'
Error for year 2001 and strategy momentum_quality_weight: 'date'
Error for year 2001 and strategy value_quality_weight: 'date'
Error for year 2002 and strategy equal_weight: 'date'
Error for year 2002 and strategy growth_quality_weight: 'date'
Error for year 2002 and strategy growth_quality_momentum_weight: 'date'
Error for year 2002 and strategy momentum_quality_weight: 'date'
Error for year 2002 and strategy value_quality_weight: 'date'
Error for year 2003 and strategy equal_weight: 'date'
Error for year 2003 and strategy growth_quality_weight: 'date'
Error for year 2003 and strategy growth_quality_momentum_weight: 'date'
Error for year 2003 and strategy momentum_quality_weight: 'date'
Error for year 2003 and strategy value_quality_weight: 'date'
Error for year 2004 and strategy equal_weight: 'date'
Error for year 2004 and strategy growth_quality_weight: 'date'
Error for year 2004 and strategy growth_quality_momentum_weight: 'date'
Error for year 2004 and strategy momentum_quality_weight: 'date'
Error for year 2004 and strategy value_quality_weight: 'date'
Error for year 2005 and strategy equal_weight: 'date'
Error for year 2005 and strategy growth_quality_weight: 'date'
Error for year 2005 and strategy growth_quality_momentum_weight: 'date'
Error for year 2005 and strategy momentum_quality_weight: 'date'
Error for year 2005 and strategy value_quality_weight: 'date'
Error for year 2006 and strategy equal_weight: 'date'
Error for year 2006 and strategy growth_quality_weight: 'date'
Error for year 2006 and strategy growth_quality_momentum_weight: 'date'
Error for year 2006 and strategy momentum_quality_weight: 'date'
Error for year 2006 and strategy value_quality_weight: 'date'
Error for year 2007 and strategy equal_weight: 'date'
Error for year 2007 and strategy growth_quality_weight: 'date'
Error for year 2007 and strategy growth_quality_momentum_weight: 'date'
Error for year 2007 and strategy momentum_quality_weight: 'date'
Error for year 2007 and strategy value_quality_weight: 'date'
Error for year 2008 and strategy equal_weight: 'date'
Error for year 2008 and strategy growth_quality_weight: 'date'
Error for year 2008 and strategy growth_quality_momentum_weight: 'date'
Error for year 2008 and strategy momentum_quality_weight: 'date'
Error for year 2008 and strategy value_quality_weight: 'date'
Error for year 2009 and strategy equal_weight: 'date'
Error for year 2009 and strategy growth_quality_weight: 'date'
Error for year 2009 and strategy growth_quality_momentum_weight: 'date'
Error for year 2009 and strategy momentum_quality_weight: 'date'
Error for year 2009 and strategy value_quality_weight: 'date'
Error for year 2010 and strategy equal_weight: 'date'
Error for year 2010 and strategy growth_quality_weight: 'date'
Error for year 2010 and strategy growth_quality_momentum_weight: 'date'
Error for year 2010 and strategy momentum_quality_weight: 'date'
Error for year 2010 and strategy value_quality_weight: 'date'
Error for year 2011 and strategy equal_weight: 'date'
Error for year 2011 and strategy growth_quality_weight: 'date'
Error for year 2011 and strategy growth_quality_momentum_weight: 'date'
Error for year 2011 and strategy momentum_quality_weight: 'date'
Error for year 2011 and strategy value_quality_weight: 'date'
Error for year 2012 and strategy equal_weight: 'date'
Error for year 2012 and strategy growth_quality_weight: 'date'
Error for year 2012 and strategy growth_quality_momentum_weight: 'date'
Error for year 2012 and strategy momentum_quality_weight: 'date'
Error for year 2012 and strategy value_quality_weight: 'date'
Error for year 2013 and strategy equal_weight: 'date'
Error for year 2013 and strategy growth_quality_weight: 'date'
Error for year 2013 and strategy growth_quality_momentum_weight: 'date'
Error for year 2013 and strategy momentum_quality_weight: 'date'
Error for year 2013 and strategy value_quality_weight: 'date'
Error for year 2014 and strategy equal_weight: 'date'
Error for year 2014 and strategy growth_quality_weight: 'date'
Error for year 2014 and strategy growth_quality_momentum_weight: 'date'
Error for year 2014 and strategy momentum_quality_weight: 'date'
Error for year 2014 and strategy value_quality_weight: 'date'
Error for year 2015 and strategy equal_weight: 'date'
Error for year 2015 and strategy growth_quality_weight: 'date'
Error for year 2015 and strategy growth_quality_momentum_weight: 'date'
Error for year 2015 and strategy momentum_quality_weight: 'date'
Error for year 2015 and strategy value_quality_weight: 'date'
Error for year 2016 and strategy equal_weight: 'date'
Error for year 2016 and strategy growth_quality_weight: 'date'
Error for year 2016 and strategy growth_quality_momentum_weight: 'date'
Error for year 2016 and strategy momentum_quality_weight: 'date'
Error for year 2016 and strategy value_quality_weight: 'date'
Error for year 2017 and strategy equal_weight: 'date'
Error for year 2017 and strategy growth_quality_weight: 'date'
Error for year 2017 and strategy growth_quality_momentum_weight: 'date'
Error for year 2017 and strategy momentum_quality_weight: 'date'
Error for year 2017 and strategy value_quality_weight: 'date'
Error for year 2018 and strategy equal_weight: 'date'
Error for year 2018 and strategy growth_quality_weight: 'date'
Error for year 2018 and strategy growth_quality_momentum_weight: 'date'
Error for year 2018 and strategy momentum_quality_weight: 'date'
Error for year 2018 and strategy value_quality_weight: 'date'
Error for year 2019 and strategy equal_weight: 'date'
Error for year 2019 and strategy growth_quality_weight: 'date'
Error for year 2019 and strategy growth_quality_momentum_weight: 'date'
Error for year 2019 and strategy momentum_quality_weight: 'date'
Error for year 2019 and strategy value_quality_weight: 'date'
Error for year 2020 and strategy equal_weight: 'date'
Error for year 2020 and strategy growth_quality_weight: 'date'
Error for year 2020 and strategy growth_quality_momentum_weight: 'date'
Error for year 2020 and strategy momentum_quality_weight: 'date'
Error for year 2020 and strategy value_quality_weight: 'date'

(     equal_weight growth_quality_weight growth_quality_momentum_weight  \
 2001          NaN                   NaN                            NaN
 2002          NaN                   NaN                            NaN
 2003          NaN                   NaN                            NaN
 2004          NaN                   NaN                            NaN
 2005          NaN                   NaN                            NaN
 2006          NaN                   NaN                            NaN
 2007          NaN                   NaN                            NaN
 2008          NaN                   NaN                            NaN
 2009          NaN                   NaN                            NaN
 2010          NaN                   NaN                            NaN
 2011          NaN                   NaN                            NaN
 2012          NaN                   NaN                            NaN
 2013          NaN                   NaN                            NaN
 2014          NaN                   NaN                            NaN
 2015          NaN                   NaN                            NaN
 2016          NaN                   NaN                            NaN
 2017          NaN                   NaN                            NaN
 2018          NaN                   NaN                            NaN
 2019          NaN                   NaN                            NaN
 2020          NaN                   NaN                            NaN

      momentum_quality_weight value_quality_weight
 2001                     NaN                  NaN
 2002                     NaN                  NaN
 2003                     NaN                  NaN
 2004                     NaN                  NaN
 2005                     NaN                  NaN
 2006                     NaN                  NaN
 2007                     NaN                  NaN
 2008                     NaN                  NaN
 2009                     NaN                  NaN
 2010                     NaN                  NaN
 2011                     NaN                  NaN
 2012                     NaN                  NaN
 2013                     NaN                  NaN
 2014                     NaN                  NaN
 2015                     NaN                  NaN
 2016                     NaN                  NaN
 2017                     NaN                  NaN
 2018                     NaN                  NaN
 2019                     NaN                  NaN
 2020                     NaN                  NaN  ,
      equal_weight growth_quality_weight growth_quality_momentum_weight  \
 2001          NaN                   NaN                            NaN
 2002          NaN                   NaN                            NaN
 2003          NaN                   NaN                            NaN
 2004          NaN                   NaN                            NaN
 2005          NaN                   NaN                            NaN
 2006          NaN                   NaN                            NaN
 2007          NaN                   NaN                            NaN
 2008          NaN                   NaN                            NaN
 2009          NaN                   NaN                            NaN
 2010          NaN                   NaN                            NaN
 2011          NaN                   NaN                            NaN
 2012          NaN                   NaN                            NaN
 2013          NaN                   NaN                            NaN
 2014          NaN                   NaN                            NaN
 2015          NaN                   NaN                            NaN
 2016          NaN                   NaN                            NaN
 2017          NaN                   NaN                            NaN
 2018          NaN                   NaN                            NaN
 2019          NaN                   NaN                            NaN
 2020          NaN                   NaN                            NaN

      momentum_quality_weight value_quality_weight
 2001                     NaN                  NaN
 2002                     NaN                  NaN
 2003                     NaN                  NaN
 2004                     NaN                  NaN
 2005                     NaN                  NaN
 2006                     NaN                  NaN
 2007                     NaN                  NaN
 2008                     NaN                  NaN
 2009                     NaN                  NaN
 2010                     NaN                  NaN
 2011                     NaN                  NaN
 2012                     NaN                  NaN
 2013                     NaN                  NaN
 2014                     NaN                  NaN
 2015                     NaN                  NaN
 2016                     NaN                  NaN
 2017                     NaN                  NaN
 2018                     NaN                  NaN
 2019                     NaN                  NaN
 2020                     NaN                  NaN  )

In [27]:
portfolio_returns_df #Date error

,equal_weight,growth_quality_weight,growth_quality_momentum_weight,momentum_quality_weight,value_quality_weight
2001,NaN,NaN,NaN,NaN,NaN
2002,NaN,NaN,NaN,NaN,NaN
2003,NaN,NaN,NaN,NaN,NaN
2004,NaN,NaN,NaN,NaN,NaN
2005,NaN,NaN,NaN,NaN,NaN
2006,NaN,NaN,NaN,NaN,NaN
2007,NaN,NaN,NaN,NaN,NaN
2008,NaN,NaN,NaN,NaN,NaN
2009,NaN,NaN,NaN,NaN,NaN
2010,NaN,NaN,NaN,NaN,NaN
2011,NaN,NaN,NaN,NaN,NaN
2012,NaN,NaN,NaN,NaN,NaN
2013,NaN,NaN,NaN,NaN,NaN
2014,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN
2016,NaN,NaN,NaN,NaN,NaN
2017,NaN,NaN,NaN,NaN,NaN
2018,NaN,NaN,NaN,NaN,NaN
2019,NaN,NaN,NaN,NaN,NaN
2020,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Define the range of years
years_range = list(range(2001, 2021))

# Initialize dictionaries to store results
return_results_by_year = {strategy: [] for strategy in strategy_weights.keys()}
volatility_results_by_year = {strategy: [] for strategy in strategy_weights.keys()}

# Iterate over each year in the range
for year in years_range:
    # Collecting the results for each strategy for the given year
    strategy_results = {}
    for strategy, weights in strategy_weights.items():
        strategy_results[strategy] = select_top_30_stocks_weighted(merged_df_final, stock_df, year, weights)

    # Averaging returns and volatility across the top 30 stocks for each strategy
    for strategy, df in strategy_results.items():
        avg_return = df['수익률(%)'].mean()
        avg_volatility = df['Volatility'].mean()
        return_results_by_year[strategy].append(avg_return)
        volatility_results_by_year[strategy].append(avg_volatility)

# Convert the summary results to DataFrames for visualization
return_df = pd.DataFrame(return_results_by_year, index=years_range)
volatility_df = pd.DataFrame(volatility_results_by_year, index=years_range)

return_df, volatility_df

<ipython-input-22-dfc20fa97237>:18: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  year_data = data[data['year'] == year].copy()  # Using copy() to avoid SettingWithCopyWarning

In [ ]:
import matplotlib.pyplot as plt

# Plotting the returns
plt.figure(figsize=(14, 7))
for column in return_df.columns:
    plt.plot(return_df.index, return_df[column], marker='', label=column)

plt.title('Average Portfolio Return (%) from 2001 to 2021')
plt.xlabel('Year')
plt.ylabel('Average Return (%)')
plt.xticks(return_df.index)  # Ensuring every year is displayed on the x-axis
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Plotting the volatilities
plt.figure(figsize=(14, 7))
for column in volatility_df.columns:
    plt.plot(volatility_df.index, volatility_df[column], marker='', label=column)

plt.title('Average Portfolio Volatility (%) from 2001 to 2021')
plt.xlabel('Year')
plt.ylabel('Average Volatility (%)')
plt.xticks(volatility_df.index)  # Ensuring every year is displayed on the x-axis
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

#Magic Formula 전략

Joel Greenblatt의 마법 공식(magic formula)를 기준으로 상위 30개의 주식들을 선택하여 포트폴리오를 구성하여  포트폴리오의 return 및 volatility를 계산 후 결과를 표와 그림으로 표현

In [37]:
merged_df_final

,code,year,month,종가(원),수정주가(원),상장주식수(주),시가총액,시가총액(천원),시가총액(조원),Symbol,...,mom_12m,mom_3m_rank,mom_6m_rank,mom_12m_rank,factor_mom,매출액(천원)_growth_rate,매출총이익(천원)_growth_rate,영업이익(천원)_growth_rate,지배주주순이익(천원)_growth_rate,GrowthFactor
0,A000020,2000,12,7159.523810,1391.285714,5.423568e+06,3.883016e+10,3.883016e+07,0.038830,A000020,...,-0.761024,1823.0,1827.0,1981.0,4.742367,NaN,NaN,NaN,NaN,NaN
1,A000020,2001,12,9269.047619,1853.809524,5.586294e+06,5.177963e+10,5.177963e+07,0.051780,A000020,...,0.077586,239.0,1691.0,205.0,-0.060720,0.059299,0.183706,0.135167,0.523976,0.225537
2,A000020,2002,12,6880.000000,1376.000000,5.586294e+06,3.843370e+10,3.843370e+07,0.038434,A000020,...,-0.362730,1669.0,1496.0,1692.0,3.451243,0.001754,0.091775,0.160605,0.227306,0.120360
3,A000020,2003,12,6724.782609,1344.956522,5.586294e+06,3.756661e+10,3.756661e+07,0.037567,A000020,...,-0.039286,1995.0,1708.0,1615.0,4.511388,-0.088406,-0.112439,-0.464955,-0.379172,-0.261243
4,A000020,2004,12,8661.739130,1732.347826,5.586294e+06,4.838702e+10,4.838702e+07,0.048387,A000020,...,0.170608,187.0,290.0,173.0,-2.391863,0.114693,0.111139,0.291107,0.222515,0.184863
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47955,A950220,2017,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,864.0,532.0,581.0,-1.766642,NaN,NaN,NaN,NaN,NaN
47956,A950220,2018,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,234.0,246.0,280.0,-3.636982,NaN,NaN,NaN,NaN,NaN
47957,A950220,2019,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,935.0,524.0,607.0,-1.780344,NaN,NaN,NaN,NaN,NaN
47958,A950220,2020,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1164.0,1275.0,822.0,0.058836,NaN,NaN,NaN,NaN,NaN
47959,A950220,2021,12,10358.260870,10358.260870,9.857114e+07,1.021030e+12,1.021030e+09,1.021030,NaN,...,-0.364628,1049.0,746.0,1835.0,0.600379,NaN,NaN,NaN,NaN,NaN

In [38]:
# Drop duplicates based on 'Symbol' and reset the index
symbols_df = merged_df_final[['Symbol', 'Symbol Name']].drop_duplicates(subset='Symbol', keep='first').reset_index(drop=True)
symbols_df = symbols_df.drop_duplicates()
symbols_df

       Symbol Symbol Name
0     A000020        동화약품
1     A000040       KR모터스
2     A000050          경방
3     A000070       삼양홀딩스
4     A000080       하이트진로
...       ...         ...
1418  A123330          제닉
1419  A123410      코리아에프티
1420  A123420     위메이드플레이
1421  A123570         이엠넷
1422      NaN         NaN

[1423 rows x 2 columns]

In [45]:
# Re-ranking using the 'min' method to handle ties

merged_df_final['magic_ey_roc_rank'] = merged_df_final['factor_value'].rank(ascending=False) + merged_df_final['factor_quality'].rank(ascending=False,)
merged_df_final['magic_rank'] = merged_df_final['magic_ey_roc_rank'].rank()

df_invest_magic = merged_df_final.loc[merged_df_final['magic_rank'] <= 30, :]
df_invest_magic = pd.merge(df_invest_magic, symbols_df, on='Symbol', how='left')
df_invest_magic.rename(columns={'factor_value': '이익수익률', 'factor_quality': '투하자본수익률','Symbol Name_y':'Symbol Name'}, inplace=True)
df_invest_magic[['Symbol', 'Symbol Name', '이익수익률', '투하자본수익률', 'magic_rank']]

     Symbol Symbol Name     이익수익률   투하자본수익률  magic_rank
0   A009240          한샘  5.451944  4.930907        25.0
1   A012510       더존비즈온  5.896289  4.592579        28.0
2   A012510       더존비즈온  5.655728  4.787536        21.0
3   A035420       NAVER  6.094166  4.670660        14.0
4   A035420       NAVER  6.183482  4.905808         3.0
5   A035420       NAVER  6.182398  5.077349         1.0
6   A035420       NAVER  5.861165  4.981200         5.0
7   A035420       NAVER  5.784072  4.827028        13.0
8   A035420       NAVER  5.571657  5.000699        10.0
9   A035420       NAVER  5.764608  4.809206        16.0
10  A035420       NAVER  5.260111  5.035915        29.0
11  A035420       NAVER  6.220983  4.981942         2.0
12  A035420       NAVER  5.497832  4.801339        30.0
13  A035720         카카오  5.294047  5.079950        23.0
14  A039130        하나투어  5.690244  4.790916        19.0
15  A039130        하나투어  5.773237  4.844333        11.0
16  A041830         인바디  6.308421  4.455595        26.0
17  A042000        카페24  5.933463  4.975378         4.0
18  A063080      컴투스홀딩스  5.972864  4.709856        15.0
19  A066980     이엔코퍼레이션  5.673000  5.043362         8.0
20  A067160      아프리카TV  5.416330  5.048459        18.0
21  A072870       메가스터디  6.135657  4.607131        17.0
22  A072870       메가스터디  6.232967  4.752580         7.0
23  A072870       메가스터디  5.810009  4.696167        24.0
24  A078340         컴투스  5.612958  4.807851        22.0
25  A086900        메디톡스  6.086659  4.756404         9.0
26  A086900        메디톡스  6.583622  4.656723         6.0
27  A086900        메디톡스  5.716927  4.871777        12.0
28  A086900        메디톡스  6.058430  4.531388        27.0
29  A086900        메디톡스  6.280848  4.509432        20.0